name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Use cache
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: Build
      run: |
        go build -o gohakai ./...
        rm gohakai
